version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - echo "Installing dependencies..."
      - pip install -r requirements.txt -t lib
  build:
    commands:
      - echo "Zipping deployment package (required lib and VS lambda function) "
      - cd lib
      - zip -r9 ../deployment_package.zip .
      - cd ..
      - zip -g deployment_package.zip lambda_function.py
  post_build:
    commands:
      - echo "Updating AWS lambda Function with the deployment zip file"
      - aws lambda update-function-code --function-name david-github-lambda --zip-file fileb://deployment_package.zip
      - echo "DONE!!"